version: '3'
services: 
  web:
    environment: 
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:3000"
    volumes: 
      - /app/node_modules
      - .:/app
  tests:
    environment: 
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4001:3000"
    volumes: 
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
